name = "VoxelWiseSEM"
uuid = "70f72f5e-8f64-4fed-8e5a-3e142e038e52"
version = "0.1.0"
authors = ["Maximilian Ernst <maximilian.stefan.ernst@gmail.com>"]

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructuralEquationModels = "383ca8c5-e4ff-4104-b0a9-f7b279deed53"

[compat]
Arrow = "2.8.0"
BenchmarkTools = "1.6.0"
CSV = "0.10.15"
DataFrames = "1.7.0"
JLD2 = "0.5.11"
LineSearches = "7.3.0"
NIfTI = "0.6.1"
Optim = "1.12.0"
Plots = "1.40.9"
ProgressMeter = "1.10.2"
Statistics = "1.11.1"
StatsBase = "0.34.4"
StructuralEquationModels = "0.4.2"
